server:
  port: 8000

spring:
  application:
    name: apigateway-service
  profiles:
    active: local
  cloud:
    gateway:
      default-filters:
        - name: LoggingFilter
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/login
            - Method=POST

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/logout
            - Method=POST

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/tokens
            - Method=GET

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/nickname/**
            - Method=GET

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users
            - Method=POST

        - id: goal-service
          uri: lb://GOAL-SERVICE
          predicates:
            - Path=/goals/**
          filters:
            - AuthorizationFilter

        - id: feed-service
          uri: lb://FEED-SERVICE
          predicates:
            - Path=/feeds/**
          filters:
            - AuthorizationFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - AuthorizationFilter



jwt:
  secretKey: z1gWDQyOzFEV7pv5PIMhauPQen4cbXVBG8sM1SfKT6FrXm8FPnRdLUrRJqMGF4cWPMjna9mOxzAfup9SCX6QZKZikBf4iIYjevI7
