server:
  port: 8000

spring:
  application:
    name: apigateway-service
  profiles:
    active: local
  cloud:
    gateway:
      default-filters:
        - name: LoggingFilter
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/login
            - Method=POST

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/logout
            - Method=POST

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/tokens
            - Method=GET

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/nickname/**
            - Method=GET

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users
            - Method=GET, POST, PATCH
          filters:
            - UserAuthorizationFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/**
          filters:
            - AuthorizationFilter

jwt:
  secretKey: z1gWDQyOzFEV7pv5PIMhauPQen4cbXVBG8sM1SfKT6FrXm8FPnRdLUrRJqMGF4cWPMjna9mOxzAfup9SCX6QZKZikBf4iIYjevI7
